source :rubygems

gem 'sqlite3'
gem 'rails', '~>2'
gem 'rspec', '~>1'
gem 'rspec-rails', '~>1'
gem 'ruby-debug', :platforms => :ruby_18
gem 'debugger', :platforms => :ruby_19
gem 'rspec_candy', :path => '../..'

group :state_machine do
  gem 'state_machine'
end

